version: "3"

tasks:
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  migrate:
    cmds:
      - go run internal/database/migration/migration.go
  run:
    cmds:
      - air
